sequenceDiagram
    autonumber
    participant OG as Organismos gubernamentales
    participant DGR as Dir. Gestión y Registro
    participant SURI as SURI (Catálogo)
    actor CS as Coordinador SINARP

    OG->>DGR: Requerimiento de eliminación, supresión o fusión
    DGR->>DGR: Validación legal y funcional
    DGR->>SURI: Actualizar datos o desactivar fuentes
    alt Eliminación de la institución
        Note over DGR: Fin sin notificación
    else Fusión
        DGR->>CS: Notificación al coordinador SINARP
    end
